---
sudo: false
language: go
go:
  - 1.14.x
go_import_path: github.com/elastic/go-libaudit

install:
  - GO111MODULE=off go get -u github.com/elastic/go-licenser
  - go get -d -t ./...

script:
  - go mod download
  - go mod verify
  - go mod tidy && [ -z "$(git status --porcelain go.mod go.sum)" ] || (echo "Go module manifest changed. Run 'go mod tidy'" 1>&2 && exit 1)
  - go-licenser -d
  - >
    find . -name '*.go' | grep -v vendor | xargs gofmt -s -l | read &&
    echo "Code differs from gofmt's style. Run 'gofmt -s -w .'" 1>&2 && exit 1 || true
  - go test -v $(go list ./... | grep -v /vendor/)
  - GOARCH=386 go test -v $(go list ./... | grep -v /vendor/)
  - mkdir -p build/bin
  - go build -o build/bin/audit ./cmd/audit/
  - go build -o build/bin/auparse ./cmd/auparse/

deploy:
  provider: releases
  api_key:
    secure: B10BgXGb1wu0JgLQJMWfXQ8sU6t0OUtZsL6XCLLEO1XH3Lc1uTTiqi0xl38ENlRcYhVKW5gPnWe5osjcaJqOQMqKA9dYXxPN3G+9yb8cE8s10Yj+WNvF3Pvs7g4nrhrM0feoX2vtQ5T0qzdYwUNqJtE19zDj/h1IaJCd/n4k6efuRysYIbDQoDOkyLy1Vl4YahUehX2ICXgC5C18NPQNTjcCWBJyJXuTyD+bgX9jEiee3a3JjfPisZwdPaR0hgvvL4vx3c8RHEPyT2REWjET5PDryuILDqEgvuk4IDcuLCHfljN+gI6WJ4T1RmnV+5XrxvWLeqgBgee6lYvBMmlN9TFUoNXwJvI+Gk8e8nJ/eT2FskMcYwb44RCNC4tZiyjoBVJ9pkGSRbSJe6GZz/wM3vdg2EHwJp3MmgAQ63deFuuaNqYFimMOkLhG/W8ogps1ApwNLbpWEXNr6bamA+iY7lcOLbZXO0F5aTYXU7UqLEnlDhsrrrrNinosx9AdX5bpZUYXFn1N8pKQleoScGhhL4vK7//6Jq+VkOSd6gpO4HyM3tVT5f9VAmk3twZrpRtSBhg5gzlSsm2aAcWIQHZAmxnjbgz80vUTbcx4rFfJOajFesaUxPA4uIbWaAU38IurCMo8xewK1GNPCfobtJ+pwuAAA1DAUYWYYcKOB0ceYKw=
  file:
    - build/bin/audit
    - build/bin/auparse
  on:
    tags: true
    repo: elastic/go-libaudit
